version: "3.9"
name: ticket-crm-local

services:
  db:
    image: postgres
    container_name: postgres-ticketcrm-local
    restart: always
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

  migrations:
    image: api-server
    build:
      context: ../../
      dockerfile: ./docker/docker/api.Dockerfile
    env_file:
      - ".env"
    command: poetry run ./manage.py migrate
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  api:
    image: api-server
    build:
      context: ../../
      dockerfile: ./docker/docker/api.Dockerfile
      args:
        COLLECTSTATIC: "true"
    env_file:
      - ".env"
    restart: always
    command: poetry run gunicorn myapp.wsgi:application -b 0.0.0.0:8000 --workers 4 --timeout 120 --log-level info
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    networks:
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - static:/app/static

  frontend:
    image: frontend-server
    build:
      context: ../../
      dockerfile: ./docker/docker/frontend.Dockerfile
      args:
        ERVIROMENT: "local"
    env_file:
      - ".env"
    restart: always
    networks:
      - app-network
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    build:
      context: ../../
      dockerfile: ./docker/docker/nginx.Dockerfile
      args:
        CONFNAME: "nginx-local"
    restart: always
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - api
      - frontend
    networks:
      - app-network
    volumes:
      - static:/api/static

volumes:
  db:
    driver: local
  static:
    driver: local

networks:
  app-network:
    driver: bridge
