version: "3.9"
name: ticket-crm-prod
services:
  db:
    image: postgres
    container_name: postgres-ticketcrm-prod
    restart: always
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django123
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U django" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network
  migrations:
    image: api-server-migration
    build:
      context: ../
      dockerfile: ./api-server/Dockerfile
    command: poetry run ./manage.py migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
      - DB_USER=django
      - DB_PASSWORD=django123
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - app-network
  gunicorn:
    image: api-server
    build:
      context: ../
      dockerfile: ./api-server/Dockerfile
    container_name: api-server-gunicorn
    restart: always
    command: poetry run ./manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - DB_USER=django
      - DB_PASSWORD=django123
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - 8000:8000
    # env_file:
    #   - ./.env.dev
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    networks:
      - app-network
  
  frontend:
    image: frontend-server
    build:
      context: ../
      dockerfile: ./frontend-server/Dockerfile
    container_name: frontend-server
    restart: always
    # command: poetry run ./manage.py runserver 0.0.0.0:8000
    # environment:
    #   - DEBUG=True
    #   - DB_USER=django
    #   - DB_PASSWORD=django123
    #   - DB_HOST=db
    #   - DB_PORT=5432
    ports:
      - 3000:3000
    # env_file:
    #   - ./.env.dev
    # depends_on:
      # gunicorn:
      #   condition: service_healthy
    networks:
      - app-network
volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge