version: "3.9"
name: ticket-crm-dev
services:
  db:
    image: postgres
    container_name: postgres-ticketcrm
    restart: always
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django123
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U django" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local