version: "3.9"
name: ticket-crm-prod

services:
  migrations:
    image: api-server
    build:
      context: ../../
      dockerfile: ./docker/production/api.Dockerfile
    env_file:
      - ".env.production"
    command: poetry run ./manage.py migrate
    networks:
      - app-network

  api:
    image: api-server
    build:
      context: ../../
      dockerfile: ./docker/docker/api.Dockerfile
      args:
        COLLECTSTATIC: "true"
    env_file:
      - ".env.production"
    restart: always
    command: poetry run gunicorn myapp.wsgi:application -b 0.0.0.0:8000 --workers 4 --timeout 120 --log-level info
    ports:
      - 8000:8000
    depends_on:
      migrations:
        condition: service_completed_successfully
    networks:
      - app-network
    volumes:
      - static:/app/static

  frontend:
    image: frontend-server
    build:
      context: ../../
      dockerfile: ./docker/docker/frontend.Dockerfile
    env_file:
      - ".env.production"
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-network

  nginx:
    image: nginx
    build:
      context: ../../
      dockerfile: ./docker/docker/nginx.Dockerfile
      args:
        CONF_NAME: "nginx-production"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - frontend
    networks:
      - app-network
    volumes:
      - static:/api/static

volumes:
  static:
    driver: local

networks:
  app-network:
    driver: bridge
